repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.7.1'  
    hooks:
    -   id: poetry-check
    -   id: poetry-install
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
