repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.7.1'  
    hooks:
    -   id: poetry-check
    -   id: poetry-install
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
